/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangpos_testjnibase_JavaToC */

#ifndef _Included_com_wangpos_testjnibase_JavaToC
#define _Included_com_wangpos_testjnibase_JavaToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    add
 * Signature: (SS)I
 */
JNIEXPORT jint JNICALL Java_com_wangpos_testjnibase_JavaToC_add__SS
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wangpos_testjnibase_JavaToC_add__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    add
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_wangpos_testjnibase_JavaToC_add__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_wangpos_testjnibase_JavaToC_add__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_wangpos_testjnibase_JavaToC_add__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    isStart
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wangpos_testjnibase_JavaToC_isStart
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    say
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_wangpos_testjnibase_JavaToC_say__C
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangpos_testjnibase_JavaToC_say__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    say
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_wangpos_testjnibase_JavaToC_say___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    say
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wangpos_testjnibase_JavaToC_say___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_wangpos_testjnibase_JavaToC
 * Method:    testCtoJava
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangpos_testjnibase_JavaToC_testCtoJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
