/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangpos_andfixcore_MainActivity */

#ifndef _Included_com_wangpos_andfixcore_MainActivity
#define _Included_com_wangpos_andfixcore_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangpos_andfixcore_MainActivity
 * Method:    replaceNative
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_wangpos_andfixcore_MainActivity_replaceNative
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
