/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangpos_createso_TestSOUtil */

#ifndef _Included_com_wangpos_createso_TestSOUtil
#define _Included_com_wangpos_createso_TestSOUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangpos_createso_TestSOUtil
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangpos_createso_TestSOUtil_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
