/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangpos_testjnibase_CBase */

#ifndef _Included_com_wangpos_testjnibase_CBase
#define _Included_com_wangpos_testjnibase_CBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangpos_testjnibase_CBase
 * Method:    getString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangpos_testjnibase_CBase_getString__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_wangpos_testjnibase_CBase
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangpos_testjnibase_CBase_getString__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
