/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangpos_testjnibase_FFmpegUtil */

#ifndef _Included_com_wangpos_testjnibase_FFmpegUtil
#define _Included_com_wangpos_testjnibase_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangpos_testjnibase_FFmpegUtil
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wangpos_testjnibase_FFmpegUtil_test
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
